---
hero_image: images / reaction.png
theme: turkoois
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Reactie
description: Maak een spel om te zien wie de snelste reacties heeft.
original_url: https://codeclubprojects.org/en-GB/microbit/reaction
interests: spellen
technologies: microbit
site_areas: projecten
hardware: microbit
software: ''
version: 3
last_tested: 2019-03-06
steps:
  - 
    title: Inleiding
  - 
    title: Wacht!
  - 
    title: 'Uitdaging: kies je eigen afbeelding'
  - 
    title: 'Uitdaging: kies je eigen vertraging'
  - 
    title: Wachten op een winnaar
  - 
    title: Wie is de snelste?
  - 
    title: 'Uitdaging: score bijhouden'
