---
hero_image: images/reaction.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Reaction
description: Make a game to see who has the fastest reactions.
original_url: https://codeclubprojects.org/en-GB/microbit/reaction
interests: ''
technologies: ''
site_areas: codeclub, microbit
steps:
- title: Introduction
- title: Wait for it!
- title: 'Challenge: Choose your own image'
- title: 'Challenge: Choose your own delay'
- title: Waiting for a winner
- title: Who is the fastest?
- title: 'Challenge: Keep score'

