---
hero_image: images/reaction.png
theme: glaswyrdd
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Adweithio
description: Creu gêm i weld pwy sy'n adweithio gyflymaf.
original_url: https://codeclubprojects.org/en-GB/microbit/reaction
interests: gemau
technologies: microbit
site_areas: prosiectau
hardware: microbit
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Cyflwyniad
  - 
    title: Arhoswch amdani!
  - 
    title: 'Her: Dewiswch eich delwedd eich hun'
  - 
    title: 'Her: Dewiswch eich oedi eich hun'
  - 
    title: Aros am enillydd
  - 
    title: Pwy yw’r cyflymaf?
  - 
    title: 'Her: Cadw sgôr'
