---
hero_image: images/reaction.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmering-1, phys-comp-0, tillverkning-0, community-0
title: Reaction
description: Make a game to see who has the fastest reactions.
original_url: https://codeclubprojects.org/en-GB/microbit/reaction
interests: spel
technologies: microbit
site_areas: projekt
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-03-06
steps:
  - 
    title: Introduktion
  - 
    title: Wait for it!
  - 
    title: 'Challenge: Choose your own image'
  - 
    title: 'Challenge: Choose your own delay'
  - 
    title: Waiting for a winner
  - 
    title: Who is the fastest?
  - 
    title: 'Challenge: Keep score'
