---
hero_image: images/reaction.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Réflexes
description: Construis un jeu pour voir qui a les réflexes les plus rapides.
original_url: https://codeclubprojects.org/en-GB/microbit/reaction
interests: games
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: A vos marques !
- title: 'Défi: Choisis ta propre image'
- title: 'Défi: Choisis ton propre délai'
- title: Attente du gagnant
- title: Qui est le plus rapide ?
- title: 'Défi: Conserve le score'